"use client";

import { createContext, useContext, useEffect, useState } from "react";

export type Lang = "en" | "ne";

const STR: Record<Lang, Record<string, string>> = {
  en: {
    "nav.find": "Find Jobs",
    "nav.alerts": "Job Alerts",
    "nav.employers": "For Employers",
    "nav.dashboard": "Open AI Dashboard",
    "nav.companies": "Companies",
    "nav.interview": "Interview prep",
    "nav.cv": "CV Builder",
    "nav.company": "Company site",
    "foot.browse": "Browse jobs",
    "foot.alerts": "Free job alerts",
    "foot.post": "Post a job (free)",
    "jobs.title": "Jobs in Nepal & Remote",
    "jobs.sub": "{n} open roles · AI-ranked matches in the dashboard · employers post free",
    "jobs.search": "Search",
    "jobs.kw": "keyword: python, SEO, accountant…",
    "jobs.loc": "Kathmandu, Remote…",
    "jobs.allcat": "All categories",
    "jobs.cta": "Never miss a match:",
    "jobs.cta_link": "get free AI-scored alerts",
    "jobs.cta_tail": "— only pinged on strong fits.",
    "jobs.none": "No roles match yet. Employers:",
    "jobs.none_link": "post the first one — free",
    "jobs.views": "views",
    "jobs.applies": "applies",
    "job.back": "← All jobs",
    "job.apply": "Apply now ↗",
    "job.apply_email": "Apply via email",
    "job.match_cta": "Check my match score",
    "job.stats": "{v} views · {a} applies · Job ID {id}",
    "match.check": "⚡ Check my match score",
    "match.scoring": "Scoring…",
    "match.hint": "Uses your saved resume profile · instant, no upload",
    "match.noresume": "No resume saved yet — open the AI Dashboard once to add it, then come back.",
    "match.open_dash": "Open dashboard",
    "match.track": "+ Track with score",
    "match.share": "Share score",
    "match.saved": "Saved to your tracker!",
    "match.missing": "missing",
    "tab.find": "Find Jobs",
    "tab.match": "Matcher",
    "tab.cover": "Cover Letter",
    "tab.track": "Tracker",
    "tab.post": "Post a Job",
    "dash.tag": "Bulk AI ranking · resume profiles · Kanban tracker · Nepal-ready seeds · no paid LLM",
    "alerts.title": "🔔 Job alerts, with AI scores",
    "alerts.sub": "We only ping you when a new post clears your match-score bar.",
    "emp.title": "Hire faster — post free in 60 seconds",
    "emp.sub": "Instant SEO-optimized public page + JSON-LD for Google Jobs · view/apply analytics · no account needed",
    "d.resume_title": "Active resume profile",
    "d.resume_meta": "{n} chars · saved locally + to server",
    "d.upload": "Upload PDF / DOCX / TXT",
    "d.save": "Save profile",
    "d.loaded": "Resume loaded ({n} chars, PDF/DOCX/TXT supported)",
    "d.saved_profile": "Resume profile saved!",
    "d.all_sources": "All sources",
    "d.nepal_picks": "Nepal picks",
    "d.global_seed": "Global seed",
    "d.remote_only": "Remote only",
    "d.search": "Search",
    "d.score_all": "⚡ Score all vs my resume",
    "d.min_score": "Min score",
    "d.add_resume_first": "Add your resume first",
    "d.search_first": "Search jobs first",
    "d.ranked": "Ranked {n} jobs — best match first",
    "d.best_match": "Best match",
    "d.fits": "fits",
    "d.to_add": "to add",
    "d.apply": "Apply ↗",
    "d.track": "+ Track",
    "d.saved_tracker": "Saved to tracker!",
    "d.no_match": "No jobs match — lower the min-score or try another keyword.",
    "d.jd": "Job description",
    "d.score_match": "Score match",
    "d.scoring": "Scoring…",
    "d.matched": "Matched:",
    "d.missing": "Missing:",
    "d.save_score": "Save to tracker with score",
    "d.generate": "Generate",
    "d.tracked": "tracked",
    "d.name": "name",
    "d.role": "role",
    "d.company": "company",
    "d.resume_ph": "resume",
    "d.jd_ph": "job description",
    "d.avg": "avg score",
    "d.refresh": "Refresh",
    "d.empty": "Nothing tracked yet — save jobs from Find Jobs or Matcher.",
    "d.gen_post": "Generate posting",
    "d.rescore": "Re-score",
    "a.email": "Email*",
    "a.keyword": "Keyword",
    "a.category": "Category",
    "a.location": "Location",
    "a.any": "Any",
    "a.kathmandu": "Kathmandu",
    "a.check": "Only alert me on strong matches (uses my saved resume)",
    "a.min": "Minimum match score",
    "a.subscribe": "Subscribe free",
    "a.manage": "Manage my alerts",
    "a.valid_email": "Enter a valid email.",
    "a.subscribed": "Subscribed! New matches go straight to {email}.",
    "a.enter_manage": "Enter your email, then press Manage.",
    "a.active": "active alert(s)",
    "a.no_alerts": "No alerts yet for this email.",
    "a.unsubscribe": "Unsubscribe",
    "a.phone": "Mobile for SMS (optional)",
    "a.channel": "Notify me by",
    "a.ch_email": "Email",
    "a.ch_sms": "SMS",
    "a.ch_both": "Both",
    "a.bad_phone": "Enter a valid 10-digit Nepal mobile number for SMS.",
    "d.cover_note": "Letter generates in your UI language (EN/NE).",
    "auth.login": "Log in",
    "auth.register": "Create account",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.name": "Full name",
    "auth.have_account": "Already have an account? Log in",
    "auth.no_account": "New here? Create an account",
    "auth.logout": "Log out",
    "auth.profile": "My profile",
    "auth.view_public": "View public profile",
    "auth.save": "Save profile",
    "auth.saved": "Profile saved!",
    "auth.headline": "Headline",
    "auth.location": "Location",
    "auth.bio": "About",
    "auth.skills": "Skills (comma separated)",
    "auth.member_since": "Member since",
    "auth.tagline": "Your AI career copilot — sign in to sync resumes, tracker and alerts.",
    "auth.welcome": "Welcome back",
    "auth.join": "Join AutomateJob",
    "auth.public_hint": "Public profile lives at",
    "auth.forgot": "Forgot password?",
    "auth.forgot_t": "Reset password",
    "auth.forgot_d": "Enter your email — we'll send a 1-hour reset link.",
    "auth.send_link": "Send reset link",
    "auth.link_sent": "If that email exists, a reset link is on its way.",
    "auth.new_pw": "New password",
    "auth.set_pw": "Set new password",
    "auth.pw_updated": "Password updated — log in with your new password.",
    "auth.bad_link": "This reset link is invalid or expired.",
    "auth.google": "Continue with Google",
    "auth.or": "or",
    "auth.magic_link": "Email me a login link",
    "auth.magic_btn": "Send login link",
    "auth.magic_sent": "Check your inbox — the link works for 15 minutes.",
    "co.title": "Company site",
    "co.sub": "Your mini-website on AutomateJob — brand, story, open roles.",
    "co.company": "Company name",
    "co.slug": "URL slug",
    "co.tagline": "Tagline",
    "co.emoji": "Logo emoji",
    "co.theme": "Theme",
    "co.about": "About",
    "co.location": "Location",
    "co.website": "Website",
    "co.benefits": "Benefits / culture (one per line)",
    "co.save": "Publish site",
    "co.saved": "Company site live at",
    "co.login_first": "Log in to build your company site.",
    "co.view": "View public site",
    "co.openings": "open roles",
    "co.no_jobs": "No open roles right now — check back soon.",
    "co.all": "Companies hiring now",
    "co.all_sub": "Mini-sites built on AutomateJob. Yours free in 2 minutes.",
    "co.make": "Create your company site",
    "co.link_hint": "Posts you publish while logged in appear here automatically.",
    "co.deadline": "Closing date (optional)",
    "co.feature": "Boost 7d",
    "co.featured": "Featured",
    "co.feat_sent": "Boost requested — it goes live after a quick review.",
    "ats.msg_subj": "Subject",
    "ats.msg_body": "Message to candidate",
    "ats.msg_send": "Send email",
    "ats.msg_sent": "Message sent!",
    "co.own_hint": "Log in so this post links to your company site + applicants stay private to you.",
    "cv.title": "CV Builder",
    "cv.sub": "Fill once, switch templates, export PDF.",
    "cv.summary": "Professional summary",
    "cv.exp": "Experience",
    "cv.edu": "Education",
    "cv.add_exp": "Add role",
    "cv.add_edu": "Add education",
    "cv.role": "Role",
    "cv.org": "Organization",
    "cv.period": "Period",
    "cv.desc": "Description",
    "cv.school": "School / degree",
    "cv.save": "Save CV",
    "cv.saved": "CV saved!",
    "cv.pdf": "Download PDF",
    "cv.template": "Template",
    "cv.phone": "Phone",
    "cv.login_first": "Log in to build your CV.",
    "pf.projects": "Projects",
    "pf.experience": "Experience",
    "pf.add": "Add",
    "pf.link": "Link",
    "pf.tags": "Tags (comma)",
    "pf.save": "Save",
    "pf.delete": "Delete",
    "pf.empty": "Nothing here yet.",
    "vrf.send": "Verify email",
    "vrf.sent": "Verification link sent — check your inbox.",
    "vrf.badge": "Verified",
    "vrf.unverified": "Unverified",
    "ava.change": "Change photo",
    "del.zone": "Danger zone",
    "del.ask": "Delete my account and all my data",
    "del.confirm": "Type DELETE to confirm",
    "del.done": "Account deleted.",
    "team.title": "Hiring team",
    "team.add_ph": "teammate@email.com",
    "team.add": "Invite",
    "team.remove": "Remove",
    "team.empty": "Only you for now — invite teammates by email.",
    "sched.title": "Schedule interview",
    "sched.send": "Schedule & notify",
    "sched.set": "Interview set for",
    "ab.title": "Jobs abroad",
    "ab.sub": "Gulf, Malaysia, Korea, Japan — vetted posts with scam-safety first.",
    "ab.safe": "Migrant safety checklist",
    "ab.safe1": "Never pay advance fees for a job offer — legit employers don't ask.",
    "ab.safe2": "Verify the manpower agency license before signing anything.",
    "ab.safe3": "Keep copies of your contract, passport and tickets with family.",
    "ab.safe4": "Report suspicious posts with the 🚩 button — we review fast.",
    "push.title": "Push notifications",
    "push.on": "Enable on this device",
    "push.off": "Push needs HTTPS/localhost + VAPID keys on the server.",
    "end.title": "Endorse",
    "end.ph": "Your email (for uniqueness)",
    "end.done": "Thanks for endorsing!",
    "end.views": "profile views",
    "lb.title": "Top inviters",
    "dest.label": "Destination",
    "dest.nepal": "Nepal",
    "nav.abroad": "Abroad",
    "mail.title": "Email delivery (Gmail)",
    "mail.send_test": "Send test email",
    "mail.sent": "Test email sent — check the inbox (and spam).",
    "mail.not_configured": "Not configured — set SMTP_USER to a Gmail address on the server.",
    "bill.pay_now": "Pay & boost",
    "bill.paid_note": "Complete payment on eSewa to go live.",
    "bill.free_note": "Boost requested — it goes live after a quick review.",
    "soc.title": "This week's content pack",
    "soc.copy": "Copy",
    "soc.copied": "Copied!",
    "soc.card": "Download image card",
    "chat.title": "Career chat",
    "chat.sub": "Ask in plain words — jobs, salaries, alerts, prep.",
    "chat.ph": "e.g. python jobs in Lalitpur…",
    "chat.hi": "Hi! Tell me what you're looking for — a role, a salary question, or interview prep.",
    "chat.chips": "python jobs in Kathmandu|React salary|interview tips|free alerts",
    "ref.title": "Refer friends, earn SMS alerts",
    "ref.sub": "Each friend who joins gives you both {n} free SMS job alerts.",
    "ref.copy": "Copy invite",
    "ref.joined": "{n} joined",
    "ref.credits": "{n} SMS credits",
    "iv.title": "Interview prep",
    "iv.sub": "Questions generated from any job description + instant feedback on your answers.",
    "iv.jd_ph": "Paste the job description here…",
    "iv.gen": "Generate questions",
    "iv.tech": "Technical",
    "iv.beh": "Behavioral",
    "iv.tips": "Answer tips",
    "iv.practice": "Practice this one",
    "iv.answer_ph": "Type your answer (aim 60–90 seconds spoken)…",
    "iv.score": "Get feedback",
    "iv.words": "words",
    "sal.title": "Salary insights",
    "sal.sub": "Real ranges from live postings, normalized to NPR/month.",
    "sal.role": "Role / keyword",
    "sal.go": "Check",
    "sal.median": "Median range",
    "sal.based": "based on {n} postings",
    "sal.thin": "Thin data — showing what we found. More posts = sharper numbers.",
    "sal.none": "No salary data for this search yet.",
    "sal.per": "NPR / month",
    "ats.apply_now": "Apply now",
    "ats.or_site": "or apply on company site ↗",
    "ats.or_email": "or apply via email",
    "ats.apply_title": "Apply for",
    "ats.resume": "Resume / profile text*",
    "ats.cover": "Short note (optional)",
    "ats.submit": "Submit application",
    "ats.sent": "Application sent!",
    "ats.your_score": "Your instant match score",
    "ats.close": "Done",
    "ats.need_resume": "Paste your resume text first.",
    "ats.inbox": "Applicants inbox",
    "ats.pick": "Pick a post to review candidates",
    "ats.total": "applicants",
    "ats.notes": "Notes (only you see this)",
    "ats.save_notes": "Save notes",
    "ats.move": "Move to",
    "ats.remove": "Remove",
    "ats.empty": "No applications yet — share the public job link to get candidates.",
    "ats.resume_view": "Resume",
    "ats.cover_view": "Note",
    "ats.notify_note": "New applicants also email the post's contact address; candidates get emailed on stage changes.",
    "my.title": "My applications",
    "my.sub": "Everything you've applied to with your email — live stages, no account needed.",
    "my.go": "Look up",
    "my.empty": "No applications from this email yet.",
    "my.applied": "Applied",
    "rep.btn": "Report",
    "rep.title": "Report this job",
    "rep.reason": "Reason",
    "rep.details": "Details (optional)",
    "rep.send": "Send report",
    "rep.done": "Thanks — our team will review this posting.",
    "adm.title": "Moderation",
    "adm.token": "Admin token",
    "adm.load": "Load queue",
    "adm.empty": "Queue clear. Nothing reported.",
    "adm.dismiss": "Dismiss",
    "adm.del_post": "Delete post",
    "adm.need": "Enter the admin token to view the queue.",
    "land.badge": "Nepal's AI-native job platform",
    "land.title": "Find work that fits. Hire people who do.",
    "land.sub": "AI-ranked matches, instant alerts and free employer postings — for Kathmandu, Pokhara and remote, in English and Nepali.",
    "land.search_ph": "Try python, designer, accountant…",
    "land.search_btn": "Search jobs",
    "land.live": "live roles on the board",
    "land.open_dash": "Open AI dashboard",
    "land.f1t": "AI match ranking",
    "land.f1d": "Every job scored 0–100 against your resume. Apply where you actually fit.",
    "land.f2t": "Smart alerts",
    "land.f2d": "Email + SMS pings only on strong matches — in English or Nepali.",
    "land.f3t": "Free employer posts",
    "land.f3d": "Publish in 60 seconds with an SEO page Google Jobs can read.",
    "land.f4t": "Kanban tracker",
    "land.f4d": "Saved → applied → interview → offer. Your pipeline, visualized.",
    "land.f5t": "Resume profiles",
    "land.f5d": "Upload once (PDF/DOCX), reuse everywhere, synced to your account.",
    "land.f6t": "Hiring analytics",
    "land.f6d": "Views, applies and conversion per post — plus one-click PDF reports.",
    "land.how": "How it works",
    "land.s1t": "Add your resume",
    "land.s1d": "Upload or paste — our engine reads skills in seconds.",
    "land.s2t": "Get ranked matches",
    "land.s2d": "Browse the board or search 25+ live sources, best fit first.",
    "land.s3t": "Track & win",
    "land.s3d": "Save, get alerts, generate cover letters, land interviews.",
    "land.emp_t": "Hiring? Post free, see stats in minutes.",
    "land.emp_d": "SEO page, view/apply analytics, PDF reports. No account needed to start.",
    "land.emp_btn": "Post a job free",
    "e.title": "Job title*",
    "e.company": "Company*",
    "e.location": "Location",
    "e.worktype": "Work type",
    "e.category": "Category",
    "e.salary": "Salary",
    "e.skills": "Skills (comma separated)",
    "e.apply_url": "Apply URL (optional)",
    "e.contact": "Contact email",
    "e.desc": "Description*",
    "e.desc_ph": "Role, responsibilities, requirements, benefits…",
    "e.draft": "✨ AI-draft description",
    "e.publish": "Publish free →",
    "e.live": "Live on the board",
    "e.delete": "Delete",
    "e.analytics": "📊 Performance — views & applies over time",
    "e.click_chart": "Click a post for its 14-day chart.",
    "e.total_line": "{v} total views · {a} total applies across {n} posts.",
    "e.last_days": "last {n} days",
    "e.pdf": "🖨️ PDF report",
    "e.enter_first": "Enter title + company first, then AI-draft.",
    "e.draft_ready": "AI draft ready — edit, then publish.",
    "e.required": "Title, company and description are required.",
    "e.published": "Published! Public page:",
  },
  ne: {
    "nav.find": "जागिर खोज्नुहोस्",
    "nav.alerts": "जागिर अलर्ट",
    "nav.employers": "रोजगारदाताका लागि",
    "nav.dashboard": "AI ड्यासबोर्ड खोल्नुहोस्",
    "nav.companies": "कम्पनीहरू",
    "nav.interview": "अन्तर्वार्ता तयारी",
    "nav.cv": "CV बिल्डर",
    "nav.company": "कम्पनी साइट",
    "foot.browse": "जागिरहरू हेर्नुहोस्",
    "foot.alerts": "निःशुल्क जागिर अलर्ट",
    "foot.post": "निःशुल्क जागिर पोस्ट गर्नुहोस्",
    "jobs.title": "नेपाल र रिमोटमा जागिरहरू",
    "jobs.sub": "{n} खुला पदहरू · ड्यासबोर्डमा AI-र्‍याङ्किङ · रोजगारदाताले निःशुल्क पोस्ट गर्नुहोस्",
    "jobs.search": "खोज्नुहोस्",
    "jobs.kw": "कीवर्ड: python, SEO, accountant…",
    "jobs.loc": "काठमाडौं, रिमोट…",
    "jobs.allcat": "सबै श्रेणीहरू",
    "jobs.cta": "कुनै मौका नछुटाउनुहोस्:",
    "jobs.cta_link": "निःशुल्क AI-स्कोर अलर्ट पाउनुहोस्",
    "jobs.cta_tail": "— बलियो मेलमा मात्र जानकारी।",
    "jobs.none": "अहिले कुनै पद छैन। रोजगारदाता:",
    "jobs.none_link": "पहिलो पोस्ट निःशुल्क गर्नुहोस्",
    "jobs.views": "अवलोकन",
    "jobs.applies": "आवेदनहरू",
    "job.back": "← सबै जागिरहरू",
    "job.apply": "अहिले आवेदन दिनुहोस् ↗",
    "job.apply_email": "इमेलबाट आवेदन",
    "job.match_cta": "मेरो म्याच स्कोर हेर्नुहोस्",
    "job.stats": "{v} अवलोकन · {a} आवेदनहरू · जागिर ID {id}",
    "match.check": "⚡ मेरो म्याच स्कोर हेर्नुहोस्",
    "match.scoring": "स्कोर गर्दै…",
    "match.hint": "तपाईंको सेभ गरिएको रिजुमे प्रयोग हुन्छ · तुरुन्त, अपलोड चाहिँदैन",
    "match.noresume": "अहिलेसम्म रिजुमे सेभ छैन — पहिले AI ड्यासबोर्डमा थप्नुहोस्।",
    "match.open_dash": "ड्यासबोर्ड खोल्नुहोस्",
    "match.track": "+ स्कोरसहित ट्र्याक गर्नुहोस्",
    "match.share": "स्कोर साझा गर्नुहोस्",
    "match.saved": "तपाईंको ट्र्याकरमा सेभ भयो!",
    "match.missing": "छुटेको",
    "tab.find": "जागिर खोज्नुहोस्",
    "tab.match": "म्याचर",
    "tab.cover": "कभर लेटर",
    "tab.track": "ट्र्याकर",
    "tab.post": "जागिर पोस्ट",
    "dash.tag": "बल्क AI र्‍याङ्किङ · रिजुमे प्रोफाइल · कानबन ट्र्याकर · नेपाल-रेडी · निःशुल्क AI",
    "alerts.title": "🔔 AI स्कोरसहित जागिर अलर्ट",
    "alerts.sub": "नयाँ पोस्टले तपाईंको म्याच-स्कोर पार गर्दा मात्र जानकारी पाउनुहोस्।",
    "emp.title": "छिटो नियुक्ति — ६० सेकेन्डमा निःशुल्क पोस्ट",
    "emp.sub": "तुरुन्त SEO पेज + Google Jobs JSON-LD · अवलोकन/आवेदन तथ्याङ्क · खाता चाहिँदैन",
    "d.resume_title": "सक्रिय रिजुमे प्रोफाइल",
    "d.resume_meta": "{n} अक्षर · स्थानीय + सर्भरमा सेभ",
    "d.upload": "PDF / DOCX / TXT अपलोड",
    "d.save": "प्रोफाइल सेभ गर्नुहोस्",
    "d.loaded": "रिजुमे लोड भयो ({n} अक्षर, PDF/DOCX/TXT समर्थित)",
    "d.saved_profile": "रिजुमे प्रोफाइल सेभ भयो!",
    "d.all_sources": "सबै स्रोतहरू",
    "d.nepal_picks": "नेपाल छनोट",
    "d.global_seed": "ग्लोबल सीड",
    "d.remote_only": "रिमोट मात्र",
    "d.search": "खोज्नुहोस्",
    "d.score_all": "⚡ मेरो रिजुमेविरुद्ध सबै स्कोर गर्नुहोस्",
    "d.min_score": "न्यूनतम स्कोर",
    "d.add_resume_first": "पहिले आफ्नो रिजुमे थप्नुहोस्",
    "d.search_first": "पहिले जागिर खोज्नुहोस्",
    "d.ranked": "{n} जागिर र्‍याङ्क गरियो — उत्कृष्ट मेल पहिले",
    "d.best_match": "उत्कृष्ट मेल",
    "d.fits": "मिल्छ",
    "d.to_add": "थप्नुपर्ने",
    "d.apply": "आवेदन ↗",
    "d.track": "+ ट्र्याक",
    "d.saved_tracker": "ट्र्याकरमा सेभ भयो!",
    "d.no_match": "कुनै जागिर मिलेन — न्यूनतम स्कोर घटाउनुहोस् वा अर्को कीवर्ड प्रयास गर्नुहोस्।",
    "d.jd": "जागिर विवरण",
    "d.score_match": "म्याच स्कोर",
    "d.scoring": "स्कोर गर्दै…",
    "d.matched": "मिलेको:",
    "d.missing": "छुटेको:",
    "d.save_score": "स्कोरसहित ट्र्याकरमा सेभ गर्नुहोस्",
    "d.generate": "सिर्जना गर्नुहोस्",
    "d.tracked": "ट्र्याक गरिएको",
    "d.name": "नाम",
    "d.role": "भूमिका",
    "d.company": "कम्पनी",
    "d.resume_ph": "रिजुमे",
    "d.jd_ph": "जागिर विवरण",
    "d.avg": "औसत स्कोर",
    "d.refresh": "रिफ्रेश",
    "d.empty": "अहिलेसम्म केही ट्र्याक छैन — जागिर खोज्नुहोस् वा म्याचरबाट सेभ गर्नुहोस्।",
    "d.gen_post": "पोस्टिङ सिर्जना गर्नुहोस्",
    "d.rescore": "पुनः स्कोर",
    "a.email": "इमेल*",
    "a.keyword": "कीवर्ड",
    "a.category": "श्रेणी",
    "a.location": "स्थान",
    "a.any": "कुनै पनि",
    "a.kathmandu": "काठमाडौं",
    "a.check": "बलियो मेलमा मात्र अलर्ट (मेरो सेभ रिजुमे प्रयोग)",
    "a.min": "न्यूनतम म्याच स्कोर",
    "a.subscribe": "निःशुल्क सदस्यता",
    "a.manage": "मेरा अलर्टहरू",
    "a.valid_email": "मान्य इमेल हाल्नुहोस्।",
    "a.subscribed": "सदस्यता भयो! नयाँ मेलहरू {email} मा जान्छन्।",
    "a.enter_manage": "आफ्नो इमेल हालेर Manage थिच्नुहोस्।",
    "a.active": "सक्रिय अलर्ट",
    "a.no_alerts": "यो इमेलका लागि अहिलेसम्म अलर्ट छैन।",
    "a.unsubscribe": "सदस्यता हटाउनुहोस्",
    "a.phone": "SMS का लागि मोबाइल (वैकल्पिक)",
    "a.channel": "जानकारी पाउने माध्यम",
    "a.ch_email": "इमेल",
    "a.ch_sms": "SMS",
    "a.ch_both": "दुवै",
    "a.bad_phone": "SMS का लागि मान्य १०-अङ्कको नेपाल मोबाइल नम्बर हाल्नुहोस्।",
    "d.cover_note": "पत्र तपाईंको UI भाषामा बन्छ (EN/NE)।",
    "auth.login": "लगइन",
    "auth.register": "खाता बनाउनुहोस्",
    "auth.email": "इमेल",
    "auth.password": "पासवर्ड",
    "auth.name": "पूरा नाम",
    "auth.have_account": "खाता छ? लगइन गर्नुहोस्",
    "auth.no_account": "नयाँ हुनुहुन्छ? खाता बनाउनुहोस्",
    "auth.logout": "लगआउट",
    "auth.profile": "मेरो प्रोफाइल",
    "auth.view_public": "सार्वजनिक प्रोफाइल हेर्नुहोस्",
    "auth.save": "प्रोफाइल सेभ गर्नुहोस्",
    "auth.saved": "प्रोफाइल सेभ भयो!",
    "auth.headline": "हेडलाइन",
    "auth.location": "स्थान",
    "auth.bio": "बारेमा",
    "auth.skills": "सीपहरू (कमा छुट्याइएको)",
    "auth.member_since": "सदस्यता",
    "auth.tagline": "तपाईंको AI करियर साथी — रिजुमे, ट्र्याकर र अलर्ट सिङ्क गर्न साइन इन गर्नुहोस्।",
    "auth.welcome": "फेरि स्वागत छ",
    "auth.join": "AutomateJob मा जोडिनुहोस्",
    "auth.public_hint": "सार्वजनिक प्रोफाइल यहाँ छ",
    "auth.forgot": "पासवर्ड बिर्सनुभयो?",
    "auth.forgot_t": "पासवर्ड रिसेट",
    "auth.forgot_d": "इमेल हाल्नुहोस् — १-घण्टे रिसेट लिङ्क पठाउँछौं।",
    "auth.send_link": "रिसेट लिङ्क पठाउनुहोस्",
    "auth.link_sent": "त्यो इमेल भएमा रिसेट लिङ्क पठाइएको छ।",
    "auth.new_pw": "नयाँ पासवर्ड",
    "auth.set_pw": "नयाँ पासवर्ड राख्नुहोस्",
    "auth.pw_updated": "पासवर्ड अपडेट भयो — नयाँ पासवर्डले लगइन गर्नुहोस्।",
    "auth.bad_link": "यो रिसेट लिङ्क अमान्य वा म्याद सकिएको छ।",
    "auth.google": "Google बाट जारी राख्नुहोस्",
    "auth.or": "वा",
    "auth.magic_link": "लगइन लिङ्क इमेल गर्नुहोस्",
    "auth.magic_btn": "लगइन लिङ्क पठाउनुहोस्",
    "auth.magic_sent": "इनबक्स हेर्नुहोस् — लिङ्क १५ मिनेट काम गर्छ।",
    "co.title": "कम्पनी साइट",
    "co.sub": "AutomateJob मा तपाईंको मिनी-वेबसाइट — ब्रान्ड, कथा, खुला पदहरू।",
    "co.company": "कम्पनी नाम",
    "co.slug": "URL स्लग",
    "co.tagline": "ट्यागलाइन",
    "co.emoji": "लोगो इमोजी",
    "co.theme": "थिम",
    "co.about": "बारेमा",
    "co.location": "स्थान",
    "co.website": "वेबसाइट",
    "co.benefits": "सुविधा / संस्कृति (प्रति लाइन एक)",
    "co.save": "साइट प्रकाशित गर्नुहोस्",
    "co.saved": "कम्पनी साइट लाइभ:",
    "co.login_first": "कम्पनी साइट बनाउन लगइन गर्नुहोस्।",
    "co.view": "सार्वजनिक साइट हेर्नुहोस्",
    "co.openings": "खुला पदहरू",
    "co.no_jobs": "अहिले खुला पद छैन — पछि हेर्नुहोस्।",
    "co.all": "अहिले नियुक्ति गर्दै",
    "co.all_sub": "AutomateJob मा बनेका मिनी-साइटहरू। तपाईंको २ मिनेटमा निःशुल्क।",
    "co.make": "कम्पनी साइट बनाउनुहोस्",
    "co.link_hint": "लगइन गरेर प्रकाशित पोस्टहरू यहाँ स्वतः देखिन्छन्।",
    "co.deadline": "अन्तिम मिति (वैकल्पिक)",
    "co.feature": "बुस्ट ७ दिन",
    "co.featured": "फिचर्ड",
    "co.feat_sent": "बुस्ट अनुरोध पठाइयो — समीक्षापछि लाइभ हुन्छ।",
    "ats.msg_subj": "विषय",
    "ats.msg_body": "उम्मेदवारलाई सन्देश",
    "ats.msg_send": "इमेल पठाउनुहोस्",
    "ats.msg_sent": "सन्देश पठाइयो!",
    "co.own_hint": "लगइन गर्नुहोस् — पोस्ट कम्पनी साइटसँग जोडिन्छ र आवेदक तपाईंलाई मात्र देखिन्छ।",
    "cv.title": "CV बिल्डर",
    "cv.sub": "एकपटक भर्नुहोस्, टेम्प्लेट बदल्नुहोस्, PDF निकाल्नुहोस्।",
    "cv.summary": "व्यावसायिक सारांश",
    "cv.exp": "अनुभव",
    "cv.edu": "शिक्षा",
    "cv.add_exp": "भूमिका थप्नुहोस्",
    "cv.add_edu": "शिक्षा थप्नुहोस्",
    "cv.role": "भूमिका",
    "cv.org": "संस्था",
    "cv.period": "अवधि",
    "cv.desc": "विवरण",
    "cv.school": "विद्यालय / डिग्री",
    "cv.save": "CV सेभ गर्नुहोस्",
    "cv.saved": "CV सेभ भयो!",
    "cv.pdf": "PDF डाउनलोड",
    "cv.template": "टेम्प्लेट",
    "cv.phone": "फोन",
    "cv.login_first": "CV बनाउन लगइन गर्नुहोस्।",
    "pf.projects": "परियोजनाहरू",
    "pf.experience": "अनुभव",
    "pf.add": "थप्नुहोस्",
    "pf.link": "लिङ्क",
    "pf.tags": "ट्याग (कमा)",
    "pf.save": "सेभ",
    "pf.delete": "हटाउनुहोस्",
    "pf.empty": "यहाँ अहिले केही छैन।",
    "vrf.send": "इमेल प्रमाणित गर्नुहोस्",
    "vrf.sent": "प्रमाणीकरण लिङ्क पठाइयो — इनबक्स हेर्नुहोस्।",
    "vrf.badge": "प्रमाणित",
    "vrf.unverified": "अप्रमाणित",
    "ava.change": "फोटो बदल्नुहोस्",
    "del.zone": "खतरा क्षेत्र",
    "del.ask": "खाता र सबै डेटा मेट्नुहोस्",
    "del.confirm": "पुष्टि गर्न DELETE लेख्नुहोस्",
    "del.done": "खाता मेटियो।",
    "team.title": "नियुक्ति टोली",
    "team.add_ph": "सहकर्मी@इमेल.com",
    "team.add": "निम्तो",
    "team.remove": "हटाउनुहोस्",
    "team.empty": "अहिले तपाईं मात्र — इमेलबाट सहकर्मी बोलाउनुहोस्।",
    "sched.title": "अन्तर्वार्ता तालिका",
    "sched.send": "तालिका + जानकारी",
    "sched.set": "अन्तर्वार्ता तय भयो",
    "ab.title": "विदेशमा जागिर",
    "ab.sub": "खाडी, मलेसिया, कोरिया, जापान — ठगी-सुरक्षा पहिलो।",
    "ab.safe": "आप्रवासी सुरक्षा चेकलिस्ट",
    "ab.safe1": "जागिरका लागि कहिल्यै अग्रिम शुल्क नतिर्नुहोस्।",
    "ab.safe2": "हस्ताक्षरअघि म्यानपावर लाइसेन्स प्रमाणित गर्नुहोस्।",
    "ab.safe3": "करार, राहदानी र टिकटको प्रतिलिपि परिवारसँग राख्नुहोस्।",
    "ab.safe4": "शङ्कास्पद पोस्ट 🚩 बटनबाट रिपोर्ट गर्नुहोस्।",
    "push.title": "पुस सूचनाहरू",
    "push.on": "यो डिभाइसमा खोल्नुहोस्",
    "push.off": "पुसलाई HTTPS + सर्भरमा VAPID चाहिन्छ।",
    "end.title": "समर्थन गर्नुहोस्",
    "end.ph": "तपाईंको इमेल",
    "end.done": "समर्थनका लागि धन्यवाद!",
    "end.views": "प्रोफाइल अवलोकन",
    "lb.title": "उत्कृष्ट निम्तोकर्ता",
    "dest.label": "गन्तव्य",
    "dest.nepal": "नेपाल",
    "nav.abroad": "वैदेशिक",
    "mail.title": "इमेल डेलिभरी (Gmail)",
    "mail.send_test": "परीक्षण इमेल पठाउनुहोस्",
    "mail.sent": "परीक्षण इमेल पठाइयो — इनबक्स (र स्पाम) हेर्नुहोस्।",
    "mail.not_configured": "कन्फिगर छैन — सर्भरमा SMTP_USER मा Gmail ठेगाना राख्नुहोस्।",
    "bill.pay_now": "भुक्तानी + बुस्ट",
    "bill.paid_note": "लाइभ हुन eSewa मा भुक्तानी पूरा गर्नुहोस्।",
    "bill.free_note": "बुस्ट अनुरोध पठाइयो — समीक्षापछि लाइभ हुन्छ।",
    "soc.title": "यो हप्ताको कन्टेन्ट प्याक",
    "soc.copy": "कपी",
    "soc.copied": "कपी भयो!",
    "soc.card": "इमेज कार्ड डाउनलोड",
    "chat.title": "करियर च्याट",
    "chat.sub": "सजिलो भाषामा सोध्नुहोस् — जागिर, तलब, अलर्ट, तयारी।",
    "chat.ph": "जस्तै: Lalitpur मा python जागिर…",
    "chat.hi": "नमस्ते! के खोज्दै हुनुहुन्छ — भूमिका, तलब प्रश्न, वा अन्तर्वार्ता तयारी?",
    "chat.chips": "Kathmandu मा python जागिर|React तलब|अन्तर्वार्ता टिप्स|निःशुल्क अलर्ट",
    "ref.title": "साथीलाई बोलाउनुहोस्, SMS अलर्ट कमाउनुहोस्",
    "ref.sub": "जोडिने हरेक साथीले तपाईं दुवैलाई {n} निःशुल्क SMS जागिर अलर्ट।",
    "ref.copy": "निम्तो कपी गर्नुहोस्",
    "ref.joined": "{n} जोडिए",
    "ref.credits": "{n} SMS क्रेडिट",
    "iv.title": "अन्तर्वार्ता तयारी",
    "iv.sub": "कुनै पनि जागिर विवरणबाट प्रश्न + तपाईंको उत्तरमा तुरुन्त सुझाव।",
    "iv.jd_ph": "जागिर विवरण यहाँ पेस्ट गर्नुहोस्…",
    "iv.gen": "प्रश्न बनाउनुहोस्",
    "iv.tech": "प्राविधिक",
    "iv.beh": "व्यवहारिक",
    "iv.tips": "उत्तर टिप्स",
    "iv.practice": "यसको अभ्यास गर्नुहोस्",
    "iv.answer_ph": "उत्तर लेख्नुहोस् (बोल्दा ६०–९० सेकेन्ड लक्ष्य)…",
    "iv.score": "सुझाव पाउनुहोस्",
    "iv.words": "शब्द",
    "sal.title": "तलब जानकारी",
    "sal.sub": "लाइभ पोस्टिङबाट वास्तविक दायरा, NPR/महिनामा।",
    "sal.role": "भूमिका / कीवर्ड",
    "sal.go": "हेर्नुहोस्",
    "sal.median": "मध्यक दायरा",
    "sal.based": "{n} पोस्टिङमा आधारित",
    "sal.thin": "डेटा थोरै छ — भेटेको देखाउँदैछौं। धेरै पोस्ट = सही अङ्क।",
    "sal.none": "यो खोजका लागि तलब डेटा छैन।",
    "sal.per": "NPR / महिना",
    "ats.apply_now": "अहिले आवेदन दिनुहोस्",
    "ats.or_site": "वा कम्पनी साइटमा आवेदन ↗",
    "ats.or_email": "वा इमेलबाट आवेदन",
    "ats.apply_title": "आवेदन दिनुहोस्",
    "ats.resume": "रिजुमे / प्रोफाइल पाठ*",
    "ats.cover": "छोटो नोट (वैकल्पिक)",
    "ats.submit": "आवेदन पठाउनुहोस्",
    "ats.sent": "आवेदन पठाइयो!",
    "ats.your_score": "तपाईंको तुरुन्त म्याच स्कोर",
    "ats.close": "भयो",
    "ats.need_resume": "पहिले रिजुमे पाठ हाल्नुहोस्।",
    "ats.inbox": "आवेदक इनबक्स",
    "ats.pick": "उम्मेदवार हेर्न पोस्ट छान्नुहोस्",
    "ats.total": "आवेदक",
    "ats.notes": "नोट (तपाईंले मात्र देख्नुहुन्छ)",
    "ats.save_notes": "नोट सेभ गर्नुहोस्",
    "ats.move": "सार्नुहोस्",
    "ats.remove": "हटाउनुहोस्",
    "ats.empty": "अहिलेसम्म आवेदन छैन — उम्मेदवार पाउन सार्वजनिक जागिर लिङ्क बाँड्नुहोस्।",
    "ats.resume_view": "रिजुमे",
    "ats.cover_view": "नोट",
    "ats.notify_note": "नयाँ आवेदकबारे पोस्टको सम्पर्क इमेलमा जानकारी जान्छ; चरण बदलिँदा उम्मेदवारलाई इमेल जान्छ।",
    "my.title": "मेरा आवेदनहरू",
    "my.sub": "तपाईंको इमेलबाट दिएका सबै आवेदन — लाइभ चरण, खाता चाहिँदैन।",
    "my.go": "खोज्नुहोस्",
    "my.empty": "यो इमेलबाट अहिलेसम्म आवेदन छैन।",
    "my.applied": "आवेदन मिति",
    "rep.btn": "रिपोर्ट",
    "rep.title": "यो जागिर रिपोर्ट गर्नुहोस्",
    "rep.reason": "कारण",
    "rep.details": "विवरण (वैकल्पिक)",
    "rep.send": "रिपोर्ट पठाउनुहोस्",
    "rep.done": "धन्यवाद — हाम्रो टोलीले यो पोस्ट हेर्नेछ।",
    "adm.title": "मोडरेसन",
    "adm.token": "एडमिन टोकन",
    "adm.load": "क्यू लोड गर्नुहोस्",
    "adm.empty": "क्यू खाली छ।",
    "adm.dismiss": "हटाउनुहोस्",
    "adm.del_post": "पोस्ट मेट्नुहोस्",
    "adm.need": "क्यू हेर्न एडमिन टोकन हाल्नुहोस्।",
    "land.badge": "नेपालको AI-नेटिभ जागिर प्लेटफर्म",
    "land.title": "मिल्ने काम भेट्नुहोस्। मिल्ने मान्छे नियुक्त गर्नुहोस्।",
    "land.sub": "AI-र्‍याङ्किङ, तुरुन्त अलर्ट र निःशुल्क रोजगारदाता पोस्ट — काठमाडौं, पोखरा र रिमोटका लागि, अङ्ग्रेजी र नेपालीमा।",
    "land.search_ph": "python, designer, accountant प्रयास गर्नुहोस्…",
    "land.search_btn": "जागिर खोज्नुहोस्",
    "land.live": "बोर्डमा लाइभ पदहरू",
    "land.open_dash": "AI ड्यासबोर्ड खोल्नुहोस्",
    "land.f1t": "AI म्याच र्‍याङ्किङ",
    "land.f1d": "हरेक जागिर तपाईंको रिजुमेविरुद्ध ०–१०० स्कोर। मिल्ने ठाउँमा मात्र आवेदन।",
    "land.f2t": "स्मार्ट अलर्ट",
    "land.f2d": "बलियो मेलमा मात्र इमेल + SMS — अङ्ग्रेजी वा नेपालीमा।",
    "land.f3t": "निःशुल्क रोजगारदाता पोस्ट",
    "land.f3d": "६० सेकेन्डमा प्रकाशित, Google Jobs ले पढ्ने SEO पेजसहित।",
    "land.f4t": "कानबन ट्र्याकर",
    "land.f4d": "सेभ → आवेदन → अन्तर्वार्ता → अफर। तपाईंको पाइपलाइन, स्पष्ट।",
    "land.f5t": "रिजुमे प्रोफाइल",
    "land.f5d": "एकपटक अपलोड (PDF/DOCX), जताततै प्रयोग, खातामा सिङ्क।",
    "land.f6t": "नियुक्ति तथ्याङ्क",
    "land.f6d": "प्रति पोस्ट अवलोकन, आवेदन, कन्भर्सन — एक-क्लिक PDF रिपोर्टसहित।",
    "land.how": "यसले कसरी काम गर्छ",
    "land.s1t": "रिजुमे थप्नुहोस्",
    "land.s1d": "अपलोड वा पेस्ट — हाम्रो इन्जिनले सेकेन्डमा सीप पढ्छ।",
    "land.s2t": "र्‍याङ्क गरिएको मेल पाउनुहोस्",
    "land.s2d": "बोर्ड हेर्नुहोस् वा २५+ लाइभ स्रोत खोज्नुहोस्, उत्कृष्ट पहिले।",
    "land.s3t": "ट्र्याक र सफलता",
    "land.s3d": "सेभ, अलर्ट, कभर लेटर — अन्तर्वार्ता पक्का।",
    "land.emp_t": "नियुक्ति गर्दै? निःशुल्क पोस्ट, मिनेटमा तथ्याङ्क।",
    "land.emp_d": "SEO पेज, अवलोकन/आवेदन तथ्याङ्क, PDF रिपोर्ट। सुरु गर्न खाता चाहिँदैन।",
    "land.emp_btn": "निःशुल्क जागिर पोस्ट गर्नुहोस्",
    "e.title": "जागिर शीर्षक*",
    "e.company": "कम्पनी*",
    "e.location": "स्थान",
    "e.worktype": "कामको प्रकार",
    "e.category": "श्रेणी",
    "e.salary": "तलब",
    "e.skills": "सीपहरू (कमा छुट्याइएको)",
    "e.apply_url": "आवेदन URL (वैकल्पिक)",
    "e.contact": "सम्पर्क इमेल",
    "e.desc": "विवरण*",
    "e.desc_ph": "भूमिका, जिम्मेवारी, आवश्यकता, सुविधा…",
    "e.draft": "✨ AI-ड्राफ्ट विवरण",
    "e.publish": "निःशुल्क प्रकाशित →",
    "e.live": "बोर्डमा लाइभ",
    "e.delete": "हटाउनुहोस्",
    "e.analytics": "📊 प्रदर्शन — समयसँग अवलोकन र आवेदन",
    "e.click_chart": "पोस्टमा क्लिक गरेर १४-दिने चार्ट हेर्नुहोस्।",
    "e.total_line": "{v} कुल अवलोकन · {a} कुल आवेदन · {n} पोस्टहरू।",
    "e.last_days": "पछिल्लो {n} दिन",
    "e.pdf": "🖨️ PDF रिपोर्ट",
    "e.enter_first": "पहिले शीर्षक + कम्पनी हालेर AI-ड्राफ्ट गर्नुहोस्।",
    "e.draft_ready": "AI ड्राफ्ट तयार — सम्पादन गरेर प्रकाशित गर्नुहोस्।",
    "e.required": "शीर्षक, कम्पनी र विवरण आवश्यक छ।",
    "e.published": "प्रकाशित भयो! सार्वजनिक पेज:",
  },
};

const Ctx = createContext<{ lang: Lang; setLang: (l: Lang) => void }>({ lang: "en", setLang: () => {} });

export function LangProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>("en");
  useEffect(() => {
    const s = localStorage.getItem("aj_lang");
    if (s === "ne" || s === "en") {
      setLangState(s);
      document.documentElement.lang = s === "ne" ? "ne" : "en";
    }
  }, []);
  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("aj_lang", l);
    document.documentElement.lang = l === "ne" ? "ne" : "en";
  };
  return <Ctx.Provider value={{ lang, setLang }}>{children}</Ctx.Provider>;
}

export function useLang() {
  const { lang, setLang } = useContext(Ctx);
  const t = (k: string, vars?: Record<string, string | number>) => {
    let s = STR[lang][k] ?? STR.en[k] ?? k;
    if (vars) for (const [vk, vv] of Object.entries(vars)) s = s.replace(`{${vk}}`, String(vv));
    return s;
  };
  return { lang, setLang, t };
}

/** Translatable string usable inside server components. */
export function T({ k, vars, fallback }: { k: string; vars?: Record<string, string | number>; fallback?: string }) {
  const { lang } = useContext(Ctx);
  let s = STR[lang][k] ?? STR.en[k] ?? fallback ?? k;
  if (vars) for (const [vk, vv] of Object.entries(vars)) s = s.replace(`{${vk}}`, String(vv));
  return <>{s}</>;
}

export function LangToggle() {
  const { lang, setLang } = useContext(Ctx);
  return (
    <button
      onClick={() => setLang(lang === "en" ? "ne" : "en")}
      className="rounded-full border border-slate-200 bg-white px-3 py-1 text-xs font-semibold text-slate-700 hover:bg-slate-50"
      title="Switch language / भाषा परिवर्तन">
      {lang === "en" ? "🇳🇵 नेपाली" : "🇬🇧 English"}
    </button>
  );
}
