"""Skill ontology for the custom matching engine.
Curated keyword -> canonical skill mapping. No ML model download needed.
"""

SKILL_ALIASES = {
    "python": "Python",
    "django": "Django",
    "fastapi": "FastAPI",
    "flask": "Flask",
    "javascript": "JavaScript",
    "typescript": "TypeScript",
    "react": "React",
    "next.js": "Next.js",
    "nextjs": "Next.js",
    "node": "Node.js",
    "node.js": "Node.js",
    "express": "Express",
    "java": "Java",
    "spring": "Spring",
    "spring boot": "Spring Boot",
    "c#": "C#",
    ".net": ".NET",
    "golang": "Go",
    "go ": "Go",
    "rust": "Rust",
    "sql": "SQL",
    "postgres": "PostgreSQL",
    "postgresql": "PostgreSQL",
    "mysql": "MySQL",
    "mongodb": "MongoDB",
    "redis": "Redis",
    "sqlite": "SQLite",
    "aws": "AWS",
    "azure": "Azure",
    "gcp": "GCP",
    "google cloud": "GCP",
    "docker": "Docker",
    "kubernetes": "Kubernetes",
    "k8s": "Kubernetes",
    "terraform": "Terraform",
    "ci/cd": "CI/CD",
    "github actions": "GitHub Actions",
    "jenkins": "Jenkins",
    "linux": "Linux",
    "git": "Git",
    "rest": "REST APIs",
    "rest api": "REST APIs",
    "rest apis": "REST APIs",
    "graphql": "GraphQL",
    "grpc": "gRPC",
    "kafka": "Kafka",
    "rabbitmq": "RabbitMQ",
    "elasticsearch": "Elasticsearch",
    "airflow": "Airflow",
    "spark": "Spark",
    "hadoop": "Hadoop",
    "pandas": "Pandas",
    "numpy": "NumPy",
    "scikit-learn": "Scikit-learn",
    "sklearn": "Scikit-learn",
    "tensorflow": "TensorFlow",
    "pytorch": "PyTorch",
    "llm": "LLMs",
    "langchain": "LangChain",
    "openai": "OpenAI API",
    "prompt engineering": "Prompt Engineering",
    "machine learning": "Machine Learning",
    "deep learning": "Deep Learning",
    "nlp": "NLP",
    "computer vision": "Computer Vision",
    "data analysis": "Data Analysis",
    "tableau": "Tableau",
    "power bi": "Power BI",
    "excel": "Excel",
    "figma": "Figma",
    "ui/ux": "UI/UX",
    "agile": "Agile",
    "scrum": "Scrum",
    "jira": "Jira",
    "seo": "SEO",
    "hubspot": "HubSpot",
    "salesforce": "Salesforce",
    "cybersecurity": "Cybersecurity",
    "penetration testing": "Pen Testing",
    "networking": "Networking",
    "testing": "Testing",
    "jest": "Jest",
    "pytest": "PyTest",
    "cypress": "Cypress",
    "selenium": "Selenium",
    "html": "HTML",
    "css": "CSS",
    "tailwind": "Tailwind CSS",
    "vue": "Vue.js",
    "angular": "Angular",
    "svelte": "Svelte",
    "flutter": "Flutter",
    "react native": "React Native",
    "swift": "Swift",
    "kotlin": "Kotlin",
    "devops": "DevOps",
    "mlops": "MLOps",
    "linux administration": "Linux Admin",
    "bash": "Bash",
    "powershell": "PowerShell",
    "excel modeling": "Financial Modeling",
    "communication": "Communication",
    "leadership": "Leadership",
    "project management": "Project Management",
}

CANONICAL_SKILLS = sorted(set(SKILL_ALIASES.values()))

# Words that signal seniority / soft requirements (for suggestions)
SENIORITY_WORDS = ["senior", "lead", "staff", "principal", "junior", "intern", "entry"]

# Gendered / biased words to flag in job posts (simplified lexicon)
BIASED_WORDS = [
    "ninja", "rockstar", "guru", "dominant", "aggressive", "competitive",
    "maniac", "workaholic", "young", "energetic", "obedient", "submissive",
]
