import Link from 'next/link';
import { ArrowUpRight, BriefcaseBusiness, CalendarDays, ChevronRight, Sparkles, Target, Zap } from 'lucide-react';
import { applications, jobs } from '@/lib/data';

const stats=[['94%','profile strength'],['18','new matches'],['3','active applications'],['1','interview this week']];
export default function Dashboard(){return <main className="min-h-screen bg-[#08090b] text-white"><div className="mx-auto max-w-7xl px-6 py-8 lg:px-10"><header className="flex items-center justify-between border-b border-white/10 pb-6"><div><p className="text-sm text-white/40">Candidate OS / Wednesday</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Good morning, Bibash.</h1></div><Link href="/jobs" className="rounded-full bg-white px-5 py-2.5 text-sm font-medium text-black">Find jobs <ArrowUpRight className="ml-1 inline h-4 w-4"/></Link></header>
<section className="grid gap-3 py-6 sm:grid-cols-2 lg:grid-cols-4">{stats.map(([n,l])=><div key={l} className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><div className="text-2xl font-semibold">{n}</div><div className="mt-1 text-xs uppercase tracking-[.16em] text-white/35">{l}</div></div>)}</section>
<div className="grid gap-6 lg:grid-cols-[1.6fr_1fr]"><section className="rounded-3xl border border-white/10 bg-white/[.03] p-6"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2 text-sm text-white/50"><Sparkles className="h-4 w-4"/> AI match engine</div><h2 className="mt-2 text-xl font-semibold">Jobs selected for you</h2><p className="mt-1 text-sm text-white/40">Ranked by skills, preferences and career trajectory.</p></div><span className="rounded-full border border-white/10 px-3 py-1 text-xs text-white/50">Auto-refreshing</span></div><div className="mt-6 space-y-2">{jobs.slice(0,3).map(j=><Link href={`/jobs/${j.id}`} key={j.id} className="group flex items-center gap-4 rounded-2xl border border-transparent p-4 transition hover:border-white/10 hover:bg-white/[.04]"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-white text-sm font-bold text-black">{j.logo}</div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h3 className="font-medium">{j.title}</h3><span className="text-xs text-white/30">· {j.company}</span></div><p className="mt-1 text-xs text-white/35">{j.location} · {j.salary}</p></div><div className="text-right"><div className="text-sm font-semibold">{j.match}%</div><div className="text-[10px] uppercase tracking-wider text-white/30">match</div></div><ChevronRight className="h-4 w-4 text-white/20 transition group-hover:translate-x-1"/></Link>)}</div></section>
<aside className="space-y-6"><div className="rounded-3xl border border-white/10 bg-gradient-to-br from-white/[.08] to-transparent p-6"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-white text-black"><Zap className="h-5 w-5"/></div><h2 className="mt-5 text-lg font-semibold">Your agent is active</h2><p className="mt-2 text-sm leading-6 text-white/45">Watching 42 sources for roles above your 85% match threshold.</p><div className="mt-5 flex items-center justify-between border-t border-white/10 pt-4 text-xs"><span className="text-white/40">Last scan</span><span>3 min ago</span></div><Link href="/automation" className="mt-4 block text-sm text-white/70 hover:text-white">Configure automation →</Link></div><div className="rounded-3xl border border-white/10 p-6"><h2 className="font-semibold">Application pulse</h2><div className="mt-5 space-y-4">{applications.map(a=><div key={a.job} className="flex items-center gap-3"><div className="h-2 w-2 rounded-full bg-white"/><div className="flex-1"><div className="text-sm">{a.job}</div><div className="text-xs text-white/30">{a.company}</div></div><span className="text-xs text-white/50">{a.status}</span></div>)}</div><Link href="/applications" className="mt-5 flex items-center text-sm text-white/50 hover:text-white">View all applications <ArrowUpRight className="ml-1 h-3 w-3"/></Link></div></aside></div></div></main>}
